### ISSUE TITLE
ncdataset not working within parfor loop

### ISSUE THREAD

**Issue by mmmhello** [nctoolbox/nctoolbox#99]
Hi!
I have a strange problem with the nctoolbox in Matlab. I'm using Matlab 2017a. 

This simple code works:
```
for i = 1
    ds = ncdataset('D:\ECMWFgribfile.grib');
end
```

But this does not:
```
parfor i = 1
    ds = ncdataset('D:\ECMWFgribfile.grib');
end
```

I am getting the error message:
```
Warning: Escaped character '\E' is not valid. See 'doc sprintf' for supported special characters.
> In ncdataset (line 89)
  In parallel_function>make_general_channel/channel_general (line 929)
  In remoteParallelFunction (line 38)
Error using ncdataset (line 91)
Failed to open D:

Caused by:
    Undefined variable "ucar" or class "ucar.nc2.dataset.NetcdfDataset.openDataset".
```

Can anyone help me out?

**Comment by rsignell-usgs** [comment]
What were you hoping to accomplish in parallel?

**Comment by mmmhello** [comment]
Thanks for your response. I am analyzing weather data for different ship routes and I was hoping to process the grib files for each route in parallel. The simple code I posted is just the simplest code I can post that doesn't work. The strange thing is that my colleague did not get the same error message while running the parfor code with reference to a grib file on his computer. He is running Matlab 2016a on a Mac.

Do you know why the code works with for but not with parfor?

**Comment by mmmhello** [comment]
Can someone please try to run
```
parfor i = 1
    ds = ncdataset('yourgribfile.grib');
end
```
and see if they get an error message? And if you don't get an error message, let me know what version of Matlab and operating system you use?

**Comment by cjwilliamson** [comment]
I have the same error.
MATLAB 2017a
CentOS 6.8
Was this resolved? 

Thanks

**Comment by hohonuuli** [comment]
`parfor i = 1; nc = ncdataset('/Users/brian/Downloads/ERA5_spec2d.grb');end`

I didn't get an error. 

```matlab
>> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.3.0.713579 (R2017b)
MATLAB License Number: 177731
Operating System: Mac OS X  Version: 10.13 Build: 17A405 
Java Version: Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.3         (R2017b)
Statistics and Machine Learning Toolbox               Version 11.2        (R2017b)

```

**Comment by cjwilliamson** [comment]
Does this mean that the only way to use nctoolbox in parallel is with Mac?

**Comment by hohonuuli** [comment]
Not sure. Maybe the issue was addressed in the latest Matlab release. (R2017b).

**Comment by hohonuuli** [comment]
Also, just looking at the original issue:

```matlab
% Your line of code
ds = ncdataset('D:\ECMWFgribfile.grib');

% The error massage
Warning: Escaped character '\E' is not valid. See 'doc sprintf'

% This is what I'm interpreting
ds = ncdataset('D:\ECMWFgribfile.grib');
                                ^
                                `-- Escaped character '\E' is not valid
```

That seems weird that you get that in `parfor` but not `for`. But have you tried it using a relative path without the `D:\` part?

**Comment by mmmhello** [comment]
Thanks for bringing this thread back to life, cjwilliamson. No, it wasn't resolved.

I think I tried changing both the file location and file name. Since other people with Windows get the same error message I think it is a Windows / Mac thing.

**Comment by hohonuuli** [comment]
> I think it is a Windows / Mac thing.

Maybe, but I can't confirm that at this point.

**Comment by cjwilliamson** [comment]
if it is a bug in windows/linux versions of matlab... would there be anyway to correct it? does anyone have an idea of what could cause it?

**Comment by hohonuuli** [comment]
I'll install Matlab in a Windows VM and see what's going on.

**Comment by cjwilliamson** [comment]
Quick note that this is also happening on linux
